version: '3'

services:
    livro-db:
       image: mysql:5.7
       container_name: livro-db
       ports:
           - "3306:3306"
       volumes:
          - "livro_data:/var/lib/mysql"
       environment:
          MYSQL_DATABASE: livro_carga
          ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: password
  
volumes:
  livro_data:
    external: true
